// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejqjayqwrjpetikisyal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcWpheXF3cmpwZXRpa2lzeWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODE2NzcsImV4cCI6MjA2NjM1NzY3N30.Wv2QXLQkf5anFPcIq8PCW0xojw35xaLcpa7A7txHbOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);